M48
; DRILL file {KiCad 8.0.7} date 2025-01-17T16:19:06+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-17T16:19:06+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.540
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X104.21Y-92.96
X121.99Y-92.96
T2
X82.5Y-115.0
X89.5Y-49.0
X129.5Y-48.0
X141.0Y-115.0
M30
