M48
; DRILL file {KiCad 8.0.7} date 2025-01-07T01:26:13+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-07T01:26:13+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X191.0Y-81.0
T2
X178.0Y-91.5
X190.7Y-91.5
T3
X161.5Y-88.96
X161.5Y-91.5
M30
